image:
  - Visual Studio 2019

branches:
  only:
    - master

install:
  - set QTDIR=C:\Qt\5.15.2\mingw81_64
  - set PATH=%QTDIR%\bin;C:\MinGW\bin;%PATH%
  - set Qt5_DIR=C:\Qt\5.15.2\mingw81_64\lib\cmake\Qt5

build_script:
  - mkdir build
  - cd build
  - cmake.exe -G "MinGW Makefiles" ..
  - cmake.exe --build .